/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package heightconversiontool;

/**
 *
 * @author shabbir yamani
 */
public class HeightConversionTool extends javax.swing.JFrame {

    /**
     * Creates new form HeightConversion
     */
    public HeightConversionTool() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        lbl_Feet = new javax.swing.JLabel();
        lbl_Inch = new javax.swing.JLabel();
        txt_Inch = new javax.swing.JTextField();
        txt_Feet = new javax.swing.JTextField();
        btn_Convert = new javax.swing.JButton();
        txt_Cms = new javax.swing.JTextField();
        btn_Clear = new javax.swing.JButton();
        btn_Exit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lbl_Header = new javax.swing.JTextPane();
        lbl_Cms = new javax.swing.JLabel();

        jTextField3.setText("jTextField3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Heigh Conversion Tool: Feet to Centimetres");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        lbl_Feet.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Feet.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lbl_Feet.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Feet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Feet.setText("Feet");

        lbl_Inch.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Inch.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lbl_Inch.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Inch.setText("Inches");

        txt_Inch.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txt_Inch.setText("0");

        txt_Feet.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txt_Feet.setText("0");

        btn_Convert.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_Convert.setText("Convert");
        btn_Convert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ConvertActionPerformed(evt);
            }
        });

        txt_Cms.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        txt_Cms.setText("0");
        txt_Cms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CmsActionPerformed(evt);
            }
        });

        btn_Clear.setBackground(new java.awt.Color(0, 0, 0));
        btn_Clear.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_Clear.setText("Clear");
        btn_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearActionPerformed(evt);
            }
        });

        btn_Exit.setBackground(new java.awt.Color(204, 0, 0));
        btn_Exit.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        btn_Exit.setText("Exit");
        btn_Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ExitActionPerformed(evt);
            }
        });

        lbl_Header.setEditable(false);
        lbl_Header.setBackground(new java.awt.Color(102, 102, 102));
        lbl_Header.setBorder(null);
        lbl_Header.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lbl_Header.setForeground(new java.awt.Color(0, 0, 0));
        lbl_Header.setText("HEIGHT CONVERSION TOOL");
        lbl_Header.setToolTipText("");
        lbl_Header.setAutoscrolls(false);
        jScrollPane1.setViewportView(lbl_Header);

        lbl_Cms.setBackground(new java.awt.Color(0, 0, 0));
        lbl_Cms.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        lbl_Cms.setForeground(new java.awt.Color(255, 255, 255));
        lbl_Cms.setText("Centimetres");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_Cms)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_Cms, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_Clear)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_Exit))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl_Inch)
                                            .addComponent(lbl_Feet, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_Feet, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_Inch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btn_Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Feet)
                    .addComponent(txt_Feet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Inch)
                    .addComponent(txt_Inch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(btn_Convert, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cms)
                    .addComponent(txt_Cms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Exit)
                    .addComponent(btn_Clear))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void txt_CmsActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
        
    }                                       

    private void btn_ExitActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        System.exit(0);
    }                                        

    private void btn_ClearActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        txt_Feet.setText("");
        txt_Inch.setText("");
        txt_Cms.setText("");
    }                                         

    private void btn_ConvertActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
        double feet, inches, cms;
        feet = Double.parseDouble(txt_Feet.getText());
        inches = Double.parseDouble(txt_Inch.getText());
        cms = (feet*12);
        cms += inches;
        cms *= 2.54;
        txt_Cms.setText(String.valueOf(cms));
//        System.out.println(cms);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HeightConversionTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HeightConversionTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HeightConversionTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HeightConversionTool.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HeightConversionTool().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btn_Clear;
    private javax.swing.JButton btn_Convert;
    private javax.swing.JButton btn_Exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lbl_Cms;
    private javax.swing.JLabel lbl_Feet;
    private javax.swing.JTextPane lbl_Header;
    private javax.swing.JLabel lbl_Inch;
    private javax.swing.JTextField txt_Cms;
    private javax.swing.JTextField txt_Feet;
    private javax.swing.JTextField txt_Inch;
    // End of variables declaration                   
}
